Datadog Sink Connector issue #10 fix
DataDog/datadog-kafka-connect-logs pull request #32
Opened 2022-12-12 03:20 UTC by andwarnbros

Ritchie Brothers Auctioneers fix for messages <5MB causing IOException. https://github.com/DataDog/datadog-kafka-connect-logs/issues/10

### What does this PR do?
Hello I am a tech lead engineer from Ritchie Bros Auctioneers. This PR is a suggested fix for issue: [Truncate messages if compressed size exceeds 5MB](https://github.com/DataDog/datadog-kafka-connect-logs/issues/10). Instead of sending logs >5mb, when a new log is added to the batch the bytes are checked to see if had reached a new limit, the limit is below 3MB. Instead of sending one oversized batch like it does today, a new batch is created for the rest of the messages in the topic waiting for processing. If the new, new batch exceeds 3MB, another batch is created again. This process can continue until all messages are read. Once all messages are read each batch in the list of batches is then sent to Datadogs API.  The content of the IOException was also removed because the content had the complete over sized message. Kafkas default connector log size is around 1MB.

Corner cases: If one message exceeds the limit, exception is thrown but caught. We didnt want to shutdown the connector for this issue. The exception is logged as an error, along with the truncated message. 

### Motivation 
 [Truncate messages if compressed size exceeds 5MB](https://github.com/DataDog/datadog-kafka-connect-logs/issues/10). Suggests trunkating messages, but we prefer to have all messages intact, and just logging the offending message if a single message is above the limit. Also increasing the Kafka log size limit would have negative impacts on our system. So we removed the content in the IOException.  
Our connectors were constantly being shutdown when we try to send a batch of large messages exceeding 5MB to Datadog API. Kafka then tries to log the error from Datadog but Kafka logging limit is around 1MB this would also cause problems in our system. We did not want to increase the Kafka limit because processing larger messages might have a performance impact. 

### Additional Notes
Also of the limits are hardcoded. Feel free to make an suggestions

2024-04-23 20:52 UTC, jszwedko requested changes
Apologies for the long delay in review of this @andwarnbros . Given how long it has been it seems unlikely to me that you'd still be interested in pushing this forward, but feel free to reopen in the off-chance that you are 🙏 Thanks for this attempt at addressing the issue.

2024-04-23 20:52 UTC, jszwedko commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +    private boolean hasBatchOverflowed(JsonObject jsonRecord, JsonArray
I'm concerned that this implementation is fairly inefficient in that it serializes the batch to determine if it is oversized, but then throws that serialization away. I think serialization is indeed required to determine if the batch is oversized, but I'd like to see the implementation use the serialized batch to make the common case, where it doesn't need to be split, more efficient.

2024-04-23 20:52 UTC, jszwedko commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +    public static final int MAXIMUM_BATCH_MEGABYTES = 3;
Why 3 instead of 5?

2024-04-23 20:52 UTC, jszwedko commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +        }
I think this could be slightly more efficient by storing a constant of the max batch size in bytes rather than needing to do division.

2026-01-19 22:04 UTC, andwarnbros commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +    public static final int MAXIMUM_BATCH_MEGABYTES = 3;
Because we dont have any official numbers, we saw 5 but just to be safe I made it 3, to be 100% sure we dont have anymore problems.

2026-01-19 22:06 UTC, andwarnbros commented
@jszwedko @gh123man Hello we do still need this change. Did you guys finally fix this bug? If not are the mentioned changes all we need to do to be able to merge this?

2026-01-20 15:24 UTC, jszwedko commented
> @jszwedko @gh123man Hello we do still need this change. Did you guys finally fix this bug? If not are the mentioned changes all we need to do to be able to merge this?

Hey! Yes, this issue still exists. We'd be happy to see this PR picked back up if you like. I'll reopen it.

2026-01-20 15:24 UTC, jszwedko commented
I think the above comments need to be resolved and this likely needs an additional review from another team member cc/ @DataDog/agent-log-pipelines

2026-01-20 21:13 UTC, ddrthall commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +    public static final int MAXIMUM_BATCH_MEGABYTES = 3;
Official numbers are documented [here](https://docs.datadoghq.com/api/latest/logs/) - a slight buffer wouldn't necessarily be unreasonable, but we can safely push much closer to the actual limit.

2026-01-20 21:30 UTC, ddrthall commented on src/main/java/com/datadoghq/connect/logs/sink/DatadogLogsApiWriter.java
> +            if (batchRecords.size() == MINIMUM_LIST_LENGTH || jsonRecordStringBytes.length / ONE_MEGABYTE >= MAXIMUM_BATCH_MEGABYTES) {
It would be appropriate for individual entry size violation to cause truncation rather than a log drop. Not absolutley necessary for code review acceptance, given the current change is still strictly better than the old behavior.

2026-02-11 19:19 UTC, andwarnbros commented
Ok, since you will merge this fix after we fix comments, my team will be making the necessary changes to get this fix merged soon. But first we have to migrate the fork into our own org. Its not clear if we will make the changes in this PR or create a new one. So for now I will close this PR. If we have to open a new one we will reference this PR when we are ready. Thanks, I hope it won't take another 2 years to get this fix in :)

2026-02-11 19:19 UTC, closed without merging